
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris-deployment
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: tetris
  template:
    metadata:
      labels:
        app: tetris
    spec:
      containers:
        - name: tetris
<<<<<<< HEAD
          image: bsord/tetris:0.5.0 
=======
          image: lrakai/tetris:0.5.0 
>>>>>>> 726ce7d0b34e321e5b4486ff9af6e734f064d779
          ports:
            - containerPort: 80 

